### PR TITLE
add auth token for github api requests

### PR DESCRIPTION
**Pull request by akhilerm**
when the github action is being run on repositories that requires authentication to list the commits, the curl command will give a `message: Not Found`. This is fixed by adding authentication headers to curl, if an access token is being passed as an input. 

Signed-off-by: Akhil Mohan <makhil@vmware.com>

### CODE REVIEW

**Comment by akhilerm** [comment]
cc: @estesp Can you take a look at this PR?

**Review by estesp — APPROVED** [review]
LGTM

**Comment by akhilerm** [comment]
cc: @AkihiroSuda Can you also take a look at the changes?

**Review by samuelkarp — APPROVED** [review]

**Comment by akhilerm** [comment]
When will a new tag be made for this repo. Is it on demand or is there a specific process that is being followed for tagging?

**Pull request merged**
